#    Numpy Practice notes


###  Importing numpy and showing basic dimensions shape and data type of the given numpy array


In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)

1
(9,)
int64
9


In [3]:
#2d arrays
b=np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(b[0,:])  #1st row
print(b[1,:])   #2nd row
print(b[1,2])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
3


In [4]:
#way to append elements to an numpy array is done like this
arr=[]
arr=np.append(arr,[1,2,3,4,5,6,7,8,9])
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Where Function


In [43]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([5,6,7,8,9,1,2,3,4])
val=np.where(a>=b,False,True)
print(val)


[ True  True  True  True  True False False False False]


In [6]:
#matrices
#all zero matrix
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,3),99,dtype=np.int32))
print(np.random.randint(100,size=(3,3)))
print(np.identity(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[99 99 99]
 [99 99 99]
 [99 99 99]]
[[ 9 33  6]
 [11 75 76]
 [74 76 11]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#performing math functions on arrays
print(a+1)
print(a-2)
print(a*3)
print(a/4)
print(np.sin(a))
print(f'max:{np.max(a)}')
print(np.min(a))
#finding determinant using linear algebra functions
print(np.linalg.det(np.identity(3)))
print(np.linalg.trace(np.identity(3)))
print(np.linalg.eigvals(np.array([[1,2],[4,3]])))

[ 2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7]
[ 3  6  9 12 15 18 21 24 27]
[0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
max:9
1
1.0
3.0
[-1.  5.]


In [8]:
#Vertical sacking of arrays can be done using vstack and horizontal stack by hstack
print(np.vstack([a,b,b]))

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
