#    Numpy Practice notes


###  Importing numpy and showing basic dimensions shape and data type of the given numpy array


In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)

1
(9,)
int64
9


In [3]:
#2d arrays
b=np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(b[0,:])  #1st row
print(b[1,:])   #2nd row
print(b[1,2])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
3


In [4]:
#way to append elements to an numpy array is done like this
arr=[]
arr=np.append(arr,[1,2,3,4,5,6,7,8,9])
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Where Function


In [43]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([5,6,7,8,9,1,2,3,4])
val=np.where(a>=b,False,True)
print(val)


[ True  True  True  True  True False False False False]


# select function


In [ ]:
# df['something'=df.select(list_of_conditions , list of results corresponding to each condition)
'''
Example:
import numpy as np

conditions = [
    df['score'] >= 85,
    (df['score'] >= 70) & (df['score'] < 85),
    (df['score'] >= 50) & (df['score'] < 70),
    df['score'] < 50]
choices = ['A', 'B', 'C', 'F']
df['grade'] = np.select(conditions, choices)
'''

In [6]:
#matrices
#all zero matrix
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,3),99,dtype=np.int32))
print(np.random.randint(100,size=(3,3)))
print(np.identity(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[99 99 99]
 [99 99 99]
 [99 99 99]]
[[ 9 33  6]
 [11 75 76]
 [74 76 11]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#performing math functions on arrays
print(a+1)
print(a-2)
print(a*3)
print(a/4)
print(np.sin(a))
print(f'max:{np.max(a)}')
print(np.min(a))
#finding determinant using linear algebra functions
print(np.linalg.det(np.identity(3)))
print(np.linalg.trace(np.identity(3)))
print(np.linalg.eigvals(np.array([[1,2],[4,3]])))

[ 2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7]
[ 3  6  9 12 15 18 21 24 27]
[0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
max:9
1
1.0
3.0
[-1.  5.]


In [8]:
#Vertical sacking of arrays can be done using vstack and horizontal stack by hstack
print(np.vstack([a,b,b]))

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


# Numpy Practice questions

## q1: array from 1-36 and reshape it to a 6x6 matrix


In [ ]:
a=np.array(range(1,37)).reshape((6,6))
print(a)

## q2: Reduce each elements of the array by 0.15%

In [ ]:

a=np.array([92.4, 91.8, 93.1, 90.9, 91.5])
a=a-(a * 0.015)
print(a)

## Q3: A array of elements from 50 to 250 and sort elements that are greater than the mean and the count of those elements

In [ ]:
b=np.array(np.random.randint(50,150,size=100))
b=b[b>b.mean()]
print(b)
print(len(b))

## q4 Finding if a matrix is invertible or not

In [ ]:
a=np.array([[2, -1, 0],
 [1,  3, 4],
 [0, -2, 5]])
detA=np.linalg.det(a)
if detA==0:
    print('Not invertible')
else:
    print('Invertible')
    print(f'Inverse of the matrix is given by {np.linalg.inv(a)}')

## q5- Filter values where temp<20 as 20 and temp>35 to be 35

In [ ]:
temps = np.array([18, 22, 27, 30, 35, 40, 15, 10])
temps[temps<20]=20
temps[temps>35]=35
print(temps)

Hello