#Problem 1:Given a list of laptimes, convert it into seconds and store the value in a new list


In [17]:
import numpy as np
lap_times = np.array([
    "1:32.345",
    "1:31.876",
    "1:32.102",
    "1:31.654",
    "1:31.998",
    "1:32.210",
    "1:31.543",
    "1:31.889",
    "1:32.034",
    "1:31.612",
    "1:31.734",
    "1:32.156",
    "1:31.598",
    "1:31.921",
    "1:32.045"
])
s_times=list(map(lambda x:round(int(x[0])*60+float(x[2:]),3),lap_times))
print(s_times)

[92.345, 91.876, 92.102, 91.654, 91.998, 92.21, 91.543, 91.889, 92.034, 91.612, 91.734, 92.156, 91.598, 91.921, 92.045]


#Problem 2:Find the fastes lap,average laptime and consistency of the driver

In [18]:
fastest=np.min(s_times)         #Problem 2 Solution
avg=np.mean(s_times).round(3)
cons=np.std(s_times).round(3)
print(len(s_times))
print(f'Fastest lap: {fastest}')
print(f'Average lap times: {avg}')
print(f'Consistency: {cons}')

15
Fastest lap: 91.543
Average lap times: 91.914
Consistency: 0.236


#Problem 3:Finding the lap where degradation starts.(Lap after which the next 2 laps were slower)

In [19]:
p=0
deg_lap=-1
while p!=len(s_times):
    if s_times[p]<s_times[p+1]:
        if s_times[p+1]<s_times[p+2]:
            deg_lap=p
            break
        else:
            p+=1
    else:
        p+=1
print(f'Deg lap: {deg_lap+1}')


Deg lap: 4


#Problem 4:Find Out Avg Speed

In [20]:
#Creating an avg speed calculator given the distance is 5.807 km
race_dist=5.807
print(f'Race Distance:{race_dist} km\nAverage speed: {round((5.807*len(s_times)/sum(s_times))*3600,2)} kmph')

Race Distance:5.807 km
Average speed: 227.44 kmph


#Problem 5:Checking consistency if the laptimes are within 0.5 seconds of the average

In [21]:
#Consistency check
dif=list(map(lambda x:round(x-avg,3),s_times))
def is_consis(n):
    if n>=-0.5 and n<=0.5:
        return True
    else:
        return False
diff=list(filter(is_consis,dif))
print(diff)

[np.float64(0.431), np.float64(-0.038), np.float64(0.188), np.float64(-0.26), np.float64(0.084), np.float64(0.296), np.float64(-0.371), np.float64(-0.025), np.float64(0.12), np.float64(-0.302), np.float64(-0.18), np.float64(0.242), np.float64(-0.316), np.float64(0.007), np.float64(0.131)]


#Problem 6:Sector time analyser

In [22]:
laps = [
    [28.345, 30.112, 32.876],  # Lap 1
    [28.210, 30.054, 32.654],  # Lap 2
    [28.098, 29.998, 32.543],  # Lap 3
    [28.456, 30.220, 33.001],  # Lap 4
    [27.987, 29.876, 32.432],  # Lap 5
    [28.120, 30.010, 32.598],  # Lap 6
    [28.001, 29.945, 32.410],  # Lap 7
    [28.334, 30.180, 32.955]   # Lap 8
]
total_that_lap=list(map(lambda x:round(sum(x),3),laps))
print(total_that_lap)
print(f'Fastest Lap:{total_that_lap.index(np.min(total_that_lap))+1}')

[91.333, 90.918, 90.639, 91.677, 90.295, 90.728, 90.356, 91.469]
Fastest Lap:5


#Problem 8:Delta time calculator between 2 laps

In [23]:
lap1 = np.array([30.2, 30.5, 31.6])
lap2 = np.array([30.1, 30.4, 31.2])
delt=lap2-lap1
delt_full=round(np.sum(delt),3)
print(f'Delt full: {delt_full}')

Delt full: -0.6


#Problem 9:
Find the fastest lap number.

Find the average lap time.

Create a new dictionary with only laps faster than the average.

In [24]:
laps_dict = {
    1: 92.345,
    2: 91.876,
    3: 92.102,
    4: 91.654,
    5: 91.998
}
print(f'Fastest lap: {min(laps_dict.values())}')
print(f'Average Laptime:{sum(laps_dict.values())/len(laps_dict)}')
faster_than_avg={}
for i in laps_dict:
    if laps_dict[i]<sum(laps_dict.values())/len(laps_dict):
       faster_than_avg[i]=laps_dict[i]
faster_than_avg

Fastest lap: 91.654
Average Laptime:91.99499999999999


{2: 91.876, 4: 91.654}

#Problem 10:Given a list of Names,convert them all to upper cases

In [25]:
drivers = ["Verstappen", "Hamilton", "Leclerc", "Norris", "Perez"]
drivers=list(map(lambda x: x.lower(),drivers))
print(drivers)

['verstappen', 'hamilton', 'leclerc', 'norris', 'perez']


#Problem 11:Find total lap time for each lap.

Find the fastest sector 1 time.

Compute the average sector time for each sector.

In [26]:
sectors = np.array([
    [28.3, 30.1, 33.9],
    [28.1, 29.9, 33.7],
    [28.4, 30.0, 33.8]
])

print(f'Fastest Sector 1:{np.min(sectors[:,0])}')
for i,j in enumerate(sectors):
    print(f'average in sector {i+1}: {np.average(sectors[:,i])}')

Fastest Sector 1:28.1
average in sector 1: 28.26666666666667
average in sector 2: 30.0
average in sector 3: 33.8


#Problem 12:Automatically detect tyre stints

A new stint starts when lap time drops by more than 1.5s

In [27]:
laps = [
  91.2, 91.4, 91.6, 91.9, 92.3,   # Stint 1
  89.5, 89.7, 90.0,               # Stint 2 (new tyres)
  92.0, 92.4, 92.9, 93.5          # Stint 3
]
stint=[]
s=0
for i,j in enumerate(np.diff(laps)):
    if j<-1.5 or j>=1.5:
        stint.append(laps[s:i+1])
        s=i+1
stint.append(laps[s:])
for i,j in enumerate(stint):
    print(f'Stint {i+1}:{j}')

Stint 1:[91.2, 91.4, 91.6, 91.9, 92.3]
Stint 2:[89.5, 89.7, 90.0]
Stint 3:[92.0, 92.4, 92.9, 93.5]


Problem 13:VSC detection. Laps which are 25 percent slower than the median of last 3 laps.

In [32]:
laps = np.array([
  91.3, 91.5, 91.4,
  120.2, 121.0, 119.8,   # VSC
  91.6, 91.7
])
ref_lap=np.array([])
vsc=[]



[91.3]
[91.3 91.5]
[91.3 91.5 91.4]
[ 91.3  91.5  91.4 120.2]
114.375
[ 91.3  91.5  91.4 120.2 121. ]
[ 91.3  91.5  91.4 120.2 121.  119.8]
[ 91.3  91.5  91.4 120.2 121.  119.8  91.6]
[ 91.3  91.5  91.4 120.2 121.  119.8  91.6  91.7]
[np.float64(120.2)]
